#!/bin/bash
# ============================================================
# InvoiceScan AI — GCP Setup Script
# Run this AFTER setting your project ID below.
# ============================================================

# ── EDIT THIS ──
PROJECT_ID=""  # e.g., "my-invoicescan-project"

if [ -z "$PROJECT_ID" ]; then
    echo "ERROR: Set PROJECT_ID at the top of this script first."
    exit 1
fi

echo "=== Setting up GCP for InvoiceScan AI ==="
echo "Project: $PROJECT_ID"
echo ""

# Set project
gcloud config set project $PROJECT_ID

# ── 1. Enable APIs ──────────────────────────────────────────
echo "=== Enabling APIs ==="
gcloud services enable \
    documentai.googleapis.com \
    discoveryengine.googleapis.com \
    aiplatform.googleapis.com \
    generativelanguage.googleapis.com \
    sheets.googleapis.com \
    drive.googleapis.com \
    --project=$PROJECT_ID

echo "APIs enabled."

# ── 2. Create Document AI Invoice Parser ────────────────────
echo ""
echo "=== Creating Document AI Invoice Parser ==="
echo "Go to: https://console.cloud.google.com/ai/document-ai/processors?project=$PROJECT_ID"
echo ""
echo "Steps:"
echo "  1. Click 'Create Processor'"
echo "  2. Search for 'Invoice Parser'"
echo "  3. Select it and click 'Create'"
echo "  4. Copy the Processor ID from the URL"
echo "     (looks like: ab1234567890abcd)"
echo ""
read -p "Enter your Document AI Processor ID: " DOCAI_PROCESSOR_ID

# ── 3. Auth ─────────────────────────────────────────────────
echo ""
echo "=== Setting up authentication ==="
gcloud auth application-default login
echo "Auth configured."

# ── 4. Get API Key (for Gemini) ─────────────────────────────
echo ""
echo "=== Gemini API Key ==="
echo "Go to: https://aistudio.google.com/apikey"
echo "Create a key for project: $PROJECT_ID"
echo ""
read -p "Enter your Google API Key: " GOOGLE_API_KEY

# ── 5. Write .env file ─────────────────────────────────────
echo ""
echo "=== Writing server/.env ==="
cat > ../server/.env << ENVEOF
# Generated by setup_gcp.sh on $(date)
GOOGLE_GENAI_USE_VERTEXAI=FALSE
GOOGLE_API_KEY=$GOOGLE_API_KEY

GOOGLE_CLOUD_PROJECT=$PROJECT_ID
GOOGLE_CLOUD_LOCATION=us-central1

# Document AI
DOCAI_PROCESSOR_ID=$DOCAI_PROCESSOR_ID
DOCAI_LOCATION=us

# Model
GEMINI_MODEL=gemini-2.5-flash

# Sessions & Memory (local for now, switch to vertex later)
SESSION_BACKEND=memory
MEMORY_BACKEND=local
ENVEOF

echo "Created server/.env"

# ── 6. Install Python deps ──────────────────────────────────
echo ""
echo "=== Installing Python dependencies ==="
cd ../server
pip install -r requirements.txt

echo ""
echo "============================================"
echo "  Setup complete! Next steps:"
echo "============================================"
echo ""
echo "  1. Test health:    cd server && python main.py"
echo "                     curl http://localhost:8000/health"
echo ""
echo "  2. Open browser:   http://localhost:8000"
echo ""
echo "  3. Optional — set up Vertex AI Search:"
echo "     python ../scripts/setup_vertex_search.py"
echo ""
echo "  4. Optional — set up Google Sheets:"
echo "     Create a blank sheet, add SHEETS_SPREADSHEET_ID to .env"
echo ""
echo "============================================"
